window._env_ = {
  APP_PRODUCTION: "false",
  APP_BASE_URL: "http://localhost:8080",
  APP_API_VERSION: "/api/v1/",
  APP_MERCHANT: "DEFAULT",
  APP_PRODUCT_GRID_LIMIT: "15",
  APP_MAP_API_KEY: "",
  APP_NUVEI_TERMINAL_ID: "",
  APP_NUVEI_SECRET: "",
  APP_PAYMENT_TYPE_PAYTM: "PAYTM",
  APP_PAYMENT_TYPE_STRIPE: "STRIPE1",
  APP_STRIPE_KEY: "pk_test_TYooMQauvdEDq54NiTphI7jx",
  APP_THEME_COLOR: "#42f545",
};